# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-18 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('coordinates', models.CharField(max_length=100, null=True)),
                ('data', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('include_gps', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=5, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form_manager.Template')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_manager.TemplateType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form_manager.UserProfile')),
            ],
        ),
    ]
