# Generated by Django 3.0.5 on 2020-04-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
