# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-16 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_quantity', models.IntegerField()),
                ('remain_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=36)),
                ('name', models.CharField(max_length=500)),
                ('structure', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('gps', models.BooleanField(default=False)),
                ('set_name', models.CharField(max_length=36, null=True)),
                ('set_id', models.CharField(max_length=36, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=350)),
                ('last_name', models.CharField(max_length=350)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='form_manager.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_manager.Template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_manager.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_manager.UserType'),
        ),
        migrations.AddField(
            model_name='template',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_manager.TemplateType'),
        ),
        migrations.AddField(
            model_name='infotemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_manager.Template'),
        ),
        migrations.AddField(
            model_name='infotemplate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_manager.TemplateType'),
        ),
    ]
