# Generated by Django 3.0.5 on 2020-04-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PureVID', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='enviomuestra',
            name='author',
        ),
    ]
