# Generated by Django 3.0.5 on 2020-04-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PureVID', '0002_auto_20200420_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='user_lab',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
